### ISSUE TITLE
Off topic: Object Transportation Challenge Mod questions

### ISSUE THREAD

**Issue by truboxl** [ClonkAndre/Simple-Traffic-Loader#2]
Sorry a bit off topic as I don't have other means of contacting (don't like to create another account just for modding GTA4)

I am interested in your Object Transportation Challenge Mod and wondering if:

1. you will release the source for it?
2. possible to turn off the need of holding an object?
3. it can be potentially turn into a simple DYOM for GTA4 (mission types like navigating A to B if no.2 is done) since the UI is there already

You can close this once answering the questions. Once again sorry for bothering...

**Comment by ClonkAndre** [comment]
Hello,

1. Sure, i will release the source of it now. (I will create a new repository)
2. Not in the current version of the mod, but that can be implemented further on.
3. That is actually a great idea, haven't thought about that.

No problem, you didn't bother me.
You can also contact me on discord if you have any questions: ItsClonkAndre#3088

**Comment by ClonkAndre** [comment]
Created the repository: https://github.com/ClonkAndre/IV-Object-Transportation-Challenge
