### ISSUE TITLE
Retain day time and location dynamics of the original game

### ISSUE THREAD

**Issue by whoundd** [ClonkAndre/Simple-Traffic-Loader#3]
Hello ClonkAndre!

This mod is amazing, it makes the street traffic much more varied. Unfortunately, it also removes the finesse aspects that the original code has, like the influence of daytime and city location on the type and quantity of the vehicles spawned.

Examples: 
- with this mod, civilian vehicles appear inside the airfield on the Airport, instead of FlyUS vehicles.
- I don't get trashcollect trucks at late night anymore
- it seems this mod also resets the variation of less vehicles at late night and more during business hours.

Any fixes for this? Thank you for the great work.

**Comment by ClonkAndre** [comment]
So after the new version 2.0 update, you are now able to not only create area specific vehicle loading groups, but you are also able to add loading policies to groups.

The default group i quickly made that ships with Simple Traffic Loader, now requests vehicles at the Airport that fit more in it. Hopefully its better then before now 😌

The garbage trucks should also be restored, as it now got a policy that says they should only be requested in the morning.

I can't really say much about the third issue you mentioned, i can only hope it got better as i'm not sure why this would affect the vehicle density.

There might still be some things that still aren't right, so please let me know if you can find any!
I will close this for now.
